{% set name = "altgraph" %}
{% set version = "0.17.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/altgraph-{{ version }}.tar.gz
  sha256: ebf2269361b47d97b3b88e696439f6e4cbc607c17c51feb1754f90fb79839158

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - setuptools

test:
  imports:
    - altgraph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/altgraph/
  summary: Python graph (network) package
  description: |
    altgraph is a fork of graphlib: a graph (network)
    package for constructing graphs, BFS and DFS traversals,
    topological sort, shortest paths, etc. with graphviz output.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/ronaldoussoren/altgraph/
  doc_url: https://altgraph.readthedocs.io

extra:
  recipe-maintainers:
    - username
    - anthchirp
    - rth
