{% set name = "altgraph" %}
{% set version = "0.15" %}
{% set sha256 = "fc28b986a68fde8d3ff0e6d6ba3fbdd2cd562d11d45ef7c7735fbd826c9eec2e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools

test:
  imports:
    - altgraph

about:
  home: https://bitbucket.org/ronaldoussoren/altgraph
  license: MIT
  license_family: MIT
  license_file: doc/license.rst
  summary: 'altgraph is a fork of graphlib'
  description: |
      altgraph is a fork of graphlib: a graph (network)
      package for constructing graphs, BFS and DFS traversals,
      topological sort, shortest paths, etc. with graphviz output.
  doc_url: https://altgraph.readthedocs.io/en/latest/
  dev_url: https://bitbucket.org/ronaldoussoren/altgraph

extra:
  recipe-maintainers:
    - rth
