{% set name = "altgraph" %}
{% set version = "0.17.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/altgraph-{{ version }}.tar.gz
  sha256: 1b5afbb98f6c4dcadb2e2ae6ab9fa994bbb8c1d75f4fa96d340f9437ae454406

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - setuptools

test:
  imports:
    - altgraph
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/altgraph/
  summary: Python graph (network) package
  description: |
    altgraph is a fork of graphlib: a graph (network)
    package for constructing graphs, BFS and DFS traversals,
    topological sort, shortest paths, etc. with graphviz output.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/ronaldoussoren/altgraph/
  doc_url: https://altgraph.readthedocs.io

extra:
  recipe-maintainers:
    - bkpoon
    - anthchirp
    - rth
